### ISSUE TITLE
Cocoa pods are not working

### ISSUE THREAD

**Issue by acerbetti** [sebyddd/SDRecordButton#2]
Could you please upload the pod spec to the main repository?

thanks and great work

**Comment by sebyddd** [comment]
The podspec is there on the master. 
https://github.com/sebyddd/SDRecordButton/blob/master/SDRecordButton.podspec

**Comment by acerbetti** [comment]
Correct, but to make it easily available to anyone
https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by sebyddd** [comment]
Can you check now please?

**Comment by acerbetti** [comment]
Yes, it works

Thanks
