### ISSUE TITLE
"Validate" state not showing?

### ISSUE THREAD

**Issue by tciuro** [sebyddd/SDRecordButton#3]
Hello Sebastian,

Cool control, thanks for sharing! I was wondering if, as seen in your gif, the "Validate √" is missing on purpose. Is the "Validate" effect part of another control you use?

Thanks!

**Comment by sebyddd** [comment]
Hi Tito,

No, the 'Validate' effect, in the GIF, is another custom control I developed. If you're interested in it let me know. It's just a UIButton subclass with some animations :)

Best,
Sebastian
