### ISSUE TITLE
SDRecord Button not working properly with Xcode 8.0

### ISSUE THREAD

**Issue by harminderjarvics** [sebyddd/SDRecordButton#5]
I have integrated SDRecord button in my project,till the time I was using the old Xcode it was working properly,But after updating my Xcode to version 8.0, It covers my whole screen, the size of the button is gigantic now. What should I do? Help me ASAP Please!

**Comment by aChase55** [comment]
Having this same issue

**Comment by sebyddd** [comment]
Fixed in 121d0e4018b4852c69d55f6a11370686a7134abc. Please update the pod version to 1.0.3.
